CREATE TABLE IF NOT EXISTS HEADER_TEMPLATES
(
    id                    BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    organization          VARCHAR,
    organization_address  VARCHAR,
    organization_license  VARCHAR,
    organization_contacts VARCHAR,
    branch                VARCHAR,
    branch_address        VARCHAR,
    branch_license        VARCHAR,
    branch_contacts       VARCHAR,
    department            VARCHAR,
    department_address    VARCHAR,
    department_contacts   VARCHAR,
    department_license    VARCHAR,
    CONSTRAINT pk_headerTemplate PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS PAGE_TITLE_TEMPLATES
(
    id                    BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    object_type_id        BIGINT                                  NOT NULL,
    reporting_document_id BIGINT                                  NOT NULL,
    header_id             BIGINT                                  NOT NULL,
    title                 VARCHAR                                 NOT NULL,
    heading               VARCHAR                                 NOT NULL,
    object                VARCHAR,
    installation_location VARCHAR,
    address               VARCHAR,
    signature             VARCHAR,
    city                  VARCHAR,
    year                  VARCHAR,
    CONSTRAINT pk_pageTitleTemplate PRIMARY KEY (id),
    CONSTRAINT UQ_PAGE_TITLE_TEMPLATES UNIQUE (object_type_id, reporting_document_id),
    CONSTRAINT FK_PAGE_TITLE_TEMPLATES_ON_HEADER_TEMPLATES FOREIGN KEY (header_id) REFERENCES header_templates (id)
);

CREATE TABLE IF NOT EXISTS RECOMMENDATION_TEMPLATES
(
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    object_type_id      BIGINT                                  NOT NULL,
    recommendation_text VARCHAR                                 NOT NULL,
    CONSTRAINT pk_recommendationTemplate PRIMARY KEY (id),
    CONSTRAINT UQ_RECOMMENDATION_TEMPLATES UNIQUE (object_type_id, recommendation_text)
);

CREATE TABLE IF NOT EXISTS APPENDICES_TEMPLATES
(
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    sequential_number INTEGER,
    appendices_name   VARCHAR,
    CONSTRAINT pk_appendicesTemplate PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS CONCLUSION_TEMPLATES
(
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    header_text  VARCHAR,
    if_than_norm VARCHAR,
    approaching  VARCHAR,
    equal        VARCHAR,
    if_less_norm VARCHAR,
    if_no_norm   VARCHAR,
    CONSTRAINT pk_conclusionTemplate PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS COLUMNS_HEADERS_TEMPLATES
(
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    sequential_number INTEGER                                 NOT NULL,
    heading           VARCHAR                                 NOT NULL,
    CONSTRAINT pk_columnHeader PRIMARY KEY (id),
    CONSTRAINT UQ_COLUMNS_HEADERS_TEMPLATES UNIQUE (sequential_number, heading)
);

CREATE TABLE IF NOT EXISTS TABLE_TEMPLATES
(
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    sequential_number INTEGER,
    table_name        VARCHAR,
    text_before_table VARCHAR,
    text_after_table  VARCHAR,
    CONSTRAINT pk_tableTemplate PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS TABLE_COLUMNS_HEADERS_TEMPLATES
(
    table_id          BIGINT,
    columns_header_id BIGINT,
    CONSTRAINT pk_table_templates_of_columns_headers_template PRIMARY KEY (table_id, columns_header_id)
);

CREATE TABLE IF NOT EXISTS DOCUMENTATION_TEMPLATES
(
    id    BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    value VARCHAR                                 NOT NULL,
    CONSTRAINT pk_documentationTemplate PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS MEASURING_TOOL_TEMPLATES
(
    id    BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    value VARCHAR                                 NOT NULL,
    CONSTRAINT pk_measuringToolTemplate PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS CHARACTERISTICS_TEMPLATES
(
    id                        BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    sequential_number         VARCHAR                                 NOT NULL,
    characteristic_name       VARCHAR                                 NOT NULL,
    sequential_number_visible BOOLEAN                                 NOT NULL,
    CONSTRAINT pk_characteristicsSurveyObject PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS AUTO_DATA_COLLECTIONS
(
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    protocol_id         BIGINT,
    protocol_conclusion BOOLEAN,
    auto_table          BOOLEAN,
    CONSTRAINT pk_autoDataCollection PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS SUBSECTION_TEMPLATES
(
    id                        BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    sequential_number         DOUBLE PRECISION                        NOT NULL,
    subsection_name           VARCHAR                                 NOT NULL,
    user_text                 VARCHAR,
    sequential_number_visible BOOLEAN                                 NOT NULL,
    certificate_employee      VARCHAR,
    division_data             VARCHAR,
    table_id                  BIGINT,
    auto_data_id              BIGINT,
    CONSTRAINT pk_subsectionTemplate PRIMARY KEY (id),
    CONSTRAINT FK_SUBSECTION_TEMPLATES_ON_TABLE_TEMPLATES FOREIGN KEY (table_id) REFERENCES table_templates (id),
    CONSTRAINT FK_SUBSECTION_TEMPLATES_ON_AUTO_DATA_COLLECTIONS
        FOREIGN KEY (auto_data_id) REFERENCES auto_data_collections (id)
);

CREATE TABLE IF NOT EXISTS SUBSECTION_DOCUMENTATION_TEMPLATES
(
    subsection_id    BIGINT,
    documentation_id BIGINT,
    CONSTRAINT pk_subsection_templates_of_documentation_templates PRIMARY KEY (subsection_id, documentation_id)
);

CREATE TABLE IF NOT EXISTS SUBSECTION_MEASURING_TOOLS_TEMPLATES
(
    subsection_id BIGINT,
    tool_id       BIGINT,
    CONSTRAINT pk_subsection_templates_of_measuring_tool_templates PRIMARY KEY (subsection_id, tool_id)
);

CREATE TABLE IF NOT EXISTS REPORT_PROTOCOL_TEMPLATES
(
    id                      BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    reporting_document_id   BIGINT                                  NOT NULL,
    title                   VARCHAR                                 NOT NULL,
    heading                 VARCHAR                                 NOT NULL,
    user_text_after_heading VARCHAR,
    conclusion_template_id  BIGINT,
    CONSTRAINT pk_reportProtocolTemplate PRIMARY KEY (id),
    CONSTRAINT FK_REPORT_PROTOCOL_TEMPLATES_ON_CONCLUSION_TEMPLATES
        FOREIGN KEY (conclusion_template_id) REFERENCES conclusion_templates (id)
);

CREATE TABLE IF NOT EXISTS REPORT_PROTOCOL_SUBSECTION_TEMPLATES
(
    protocol_id   BIGINT,
    subsection_id BIGINT,
    CONSTRAINT pk_report_protocol_templates_of_subsection_templates PRIMARY KEY (protocol_id, subsection_id)
);

CREATE TABLE IF NOT EXISTS REPORT_PROTOCOL_TABLE_TEMPLATES
(
    protocol_id BIGINT,
    table_id    BIGINT,
    CONSTRAINT pk_report_protocol_templates_of_table_templates PRIMARY KEY (protocol_id, table_id)
);

CREATE TABLE IF NOT EXISTS SECTION_TEMPLATES
(
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    sequential_number INTEGER                                 NOT NULL,
    section_name      VARCHAR                                 NOT NULL,
    CONSTRAINT pk_sectionTemplate PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS SECTION_CHARACTERISTICS_TEMPLATES
(
    section_id        BIGINT,
    characteristic_id BIGINT,
    CONSTRAINT pk_section_templates_of_characteristics_templates PRIMARY KEY (section_id, characteristic_id)
);

CREATE TABLE IF NOT EXISTS SECTION_SUBSECTION_TEMPLATES
(
    section_id    BIGINT,
    subsection_id BIGINT,
    CONSTRAINT pk_section_templates_of_subsection_templates PRIMARY KEY (section_id, subsection_id)
);

CREATE TABLE IF NOT EXISTS SECTION_PROTOCOL_TEMPLATES
(
    section_id  BIGINT,
    protocol_id BIGINT,
    CONSTRAINT pk_section_templates_of_report_protocol_templates PRIMARY KEY (section_id, protocol_id)
);

CREATE TABLE IF NOT EXISTS SECTION_RECOMMENDATION_TEMPLATES
(
    section_id        BIGINT,
    recommendation_id BIGINT,
    CONSTRAINT pk_section_templates_of_recommendation_templates PRIMARY KEY (section_id, recommendation_id)
);

CREATE TABLE IF NOT EXISTS REPORT_TEMPLATES
(
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    page_title_id BIGINT                                  NOT NULL,
    CONSTRAINT pk_reportTemplate PRIMARY KEY (id),
    CONSTRAINT FK_REPORT_TEMPLATES_ON_PAGE_TITLE_TEMPLATES FOREIGN KEY (page_title_id) REFERENCES page_title_templates (id)
);

CREATE TABLE IF NOT EXISTS REPORT_SECTION_TEMPLATES
(
    report_id  BIGINT,
    section_id BIGINT,
    CONSTRAINT pk_report_templates_of_sections_templates PRIMARY KEY (report_id, section_id)
);

CREATE TABLE IF NOT EXISTS REPORT_APPENDICES_TEMPLATES
(
    report_id     BIGINT,
    appendices_id BIGINT,
    CONSTRAINT pk_report_templates_of_appendices_templates PRIMARY KEY (report_id, appendices_id)
);

CREATE TABLE IF NOT EXISTS PROTOCOL_TEMPLATES
(
    id                     BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    reporting_document_id  BIGINT                                  NOT NULL,
    object_type_id         BIGINT                                  NOT NULL,
    object_type            VARCHAR                                 NOT NULL,
    title                  VARCHAR                                 NOT NULL,
    heading                VARCHAR                                 NOT NULL,
    header_id              BIGINT                                  NOT NULL,
    conclusion_template_id BIGINT,
    CONSTRAINT pk_protocolTemplate PRIMARY KEY (id),
    CONSTRAINT UQ_PROTOCOL_TEMPLATES UNIQUE (object_type_id, reporting_document_id),
    CONSTRAINT FK_PROTOCOL_TEMPLATES_ON_HEADER_TEMPLATES FOREIGN KEY (header_id) REFERENCES header_templates (id),
    CONSTRAINT FK_PROTOCOL_TEMPLATES_ON_CONCLUSION_TEMPLATES FOREIGN KEY (conclusion_template_id) REFERENCES conclusion_templates (id)
);

CREATE TABLE IF NOT EXISTS PROTOCOL_CHARACTERISTICS_TEMPLATES
(
    protocol_id       BIGINT,
    characteristic_id BIGINT,
    CONSTRAINT pk_protocol_templates_of_characteristics_templates PRIMARY KEY (protocol_id, characteristic_id)
);

CREATE TABLE IF NOT EXISTS PROTOCOL_SUBSECTION_TEMPLATES
(
    protocol_id   BIGINT,
    subsection_id BIGINT,
    CONSTRAINT pk_protocol_templates_of_subsection_templates PRIMARY KEY (protocol_id, subsection_id)
);

CREATE TABLE IF NOT EXISTS PROTOCOL_TABLE_TEMPLATES
(
    protocol_id BIGINT,
    table_id    BIGINT,
    CONSTRAINT pk_protocol_templates_of_table_templates PRIMARY KEY (protocol_id, table_id)
);

CREATE TABLE IF NOT EXISTS PROTOCOL_RECOMMENDATION_TEMPLATES
(
    protocol_id       BIGINT,
    recommendation_id BIGINT,
    CONSTRAINT pk_protocol_templates_of_recommendation_templates PRIMARY KEY (protocol_id, recommendation_id)
);

CREATE TABLE IF NOT EXISTS PROTOCOL_APPENDICES_TEMPLATES
(
    protocol_id   BIGINT,
    appendices_id BIGINT,
    CONSTRAINT pk_protocol_templates_of_appendices_templates PRIMARY KEY (protocol_id, appendices_id)
);